# Generated by Django 4.1 on 2023-07-05 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='stripe_id',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
